name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decrypt deploy key
      run: ./action_deploy_key_decrypt.sh
      working-directory: ./ci
      env:
        DEPLOY_KEY_PASS: ${{ secrets.DEPLOY_KEY_PASS }}

    - name: Get yarn cache path
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ env.cache-name }}-
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-

    - name: Install node_modules
      run: yarn install

    - name: Perform semantic release
      run: yarn semantic-release -e semantic-release-monorepo
